# Generated by Django 2.2 on 2021-01-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='conf_password',
        ),
    ]
